export const CustomInputFieldType = {
  SHORT_TEXT: "SHORT_TEXT",
  LONG_TEXT: "LONG_TEXT",
  DATE: "DATE",
  OPTIONS: "OPTIONS",
  NUMBER: "NUMBER",
  PHONE: "PHONE",
  EMAIL: "EMAIL",
  FILE: "FILE",
  URL: "URL",
} as const;

export const BAITEMS = [
  // {
  //   id: "ba1",
  //   formLabel: "Bank Name *",
  //   placeholder: "example@example.com",
  //   custom_type: CustomInputFieldType.OPTIONS,
  //   type: "string",
  //   name: "bankName",
  // },

  {
    id: "ba2",
    formLabel: "Username *",
    placeholder: "Enter Bankapp username",
    custom_type: CustomInputFieldType.SHORT_TEXT,
    type: "string",
    name: "username",
  },
  {
    id: "ba3",
    formLabel: "Bank App Password *",
    placeholder: "Enter Bankapp password",
    custom_type: CustomInputFieldType.SHORT_TEXT,
    type: "password",
    name: "password",
  },
  {
    id: "ba4",
    formLabel: "Transfer Pin *",
    placeholder: "Enter Bankapp transfer pin",
    custom_type: CustomInputFieldType.SHORT_TEXT,
    type: "password",
    name: "transferPin",
  },
  {
    id: "ba5",
    formLabel: "Date of Opening *",
    placeholder: "Enter Date of release",
    custom_type: CustomInputFieldType.SHORT_TEXT,
    type: "date",
    name: "dateOfOpening",
  },
  {
    id: "ba6",
    formLabel: "email to Contact *",
    placeholder: "Enter recipient email to contact",
    custom_type: CustomInputFieldType.LONG_TEXT,
    type: "string",
    name: "emailToContact",
  },
  {
    id: "ba7",
    formLabel: "Number to Contact *",
    placeholder: "Enter recipient number to contact",
    custom_type: CustomInputFieldType.LONG_TEXT,
    type: "text",
    name: "numberToContact",
  },
  {
    id: "ba8",
    formLabel: "Extra Note *",
    placeholder: "Additional info is required",
    custom_type: CustomInputFieldType.LONG_TEXT,
    type: "text",
    name: "extraNote",
  },
];

export const SIGNUPITEMS = [
  {
    id: "s1",
    formLabel: "Email",
    placeholder: "example@example.com",
    type: "email",
    name: "email",
  },
  {
    id: "s2",
    formLabel: "First Name",
    placeholder: "First Name",
    type: "text",
    name: "firstName",
  },
  {
    id: "s3",
    formLabel: "Last Name",
    placeholder: "Last Name",
    type: "text",
    name: "lastName",
  },
  {
    id: "s6",
    formLabel: "Phone Number",
    placeholder: "9090909090",
    type: "text",
    name: "phoneNumber",
  },
  {
    id: "s4",
    formLabel: "Password",
    placeholder: "Enter password",
    type: "password",
    name: "password",
  },
  {
    id: "s5",
    formLabel: "Confirm Password",
    placeholder: "Enter Confirm password",
    type: "password",
    name: "confirmPassword",
  },

  {
    id: "s7",
    formLabel: "Emergency Contact",
    placeholder: "9090909090",
    type: "text",
    name: "emergencyContact",
  },
];
